# auto build docker image and push to docker hub

name: Build and push Docker image

on:
  push:
    branches:
      - 'bug/*'
      - 'feature/*'
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ startsWith(github.ref, 'refs/tags/') == false }}
          tags: |
            homqyy/hengine:latest
            homqyy/hengine:${{ github.ref_name }}
          context: .
          file: docker/Dockerfile